config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  resources :categories

  root 'welcome#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :description, :author, :category, :category_id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.select :category_id, options_for_select(Category.all.pluck(:name,:id)) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Author</th>
      <th>Category</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.description %></td>
        <td><%= blog.author %></td>
        <td><%= blog.category %></td>
        <td><%= blog.category %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @blog.description %>
</p>

<p>
  <strong>Author:</strong>
  <%= @blog.author %>
</p>

<p>
  <strong>Category:</strong>
  <%= @blog.category.name %>
</p>



<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<% @category.blogs.each do |x|%>
	<%= x.title %><br>
	<%= x.description %><br>
	<%= x.author %><br>
<% end %>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>



   <div class="mainbox">
     <div class="fix">
       <div class="abso first" data-scroll-speed="2">
       <h2 class="text-colorb"><%= @category.blogs.last.title %></h2>
       <p style="font-size: 10px"><i>-<%= @category.blogs.last.author %> </i><%= @category.blogs.last.created_at.strftime("%b %d, %Y") %></p>
       <div class="spacer"></div>
       <p><%= @category.blogs.last.description %></p>
         <div class="spacer"></div>
         <div class="bottom-border">
         <div class="com-btn right">
           <a class="waves-effect waves-teal btn-flat">Like</a><a class="waves-effect waves-teal btn-flat ">Comment</a>
         </div>
         </div>

         <div class="spacer"></div>
         <div class="comments">
           <h3 class="text-colorb">User name</h3>
           <p style="font-size: 10px" >(dd/mm/yy)</p>
           <div class="comment-box ">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</div>

         </div>

         <div class="spacer"></div>
         <div class="comments">
           <h3 class="text-colorb">User name</h3>
           <p style="font-size: 10px" >(dd/mm/yy)</p>
           <div class="comment-box ">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</div>

         </div>
                
                  <div class="spacer"></div>
                   <div class="row">
    <form class="col s12">
      <div class="row">
        <div class="input-field col s6">
          <i class="material-icons prefix">account_circle</i>
          <input id="icon_prefix" type="text" class="validate">
          <label for="icon_prefix">First Name</label>
        </div>
        <div class="input-field col s6">
          <i class="material-icons prefix">email</i>
          <input id="icon_telephone" type="tel" class="validate">
          <label for="icon_telephone">E-mail</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
         <i class="material-icons prefix">textsms</i>
          <textarea id="textarea1" class="materialize-textarea"></textarea>
          <label for="textarea1">Comment</label>
        </div>
      </div>
        <button class="btn waves-effect waves-light " type="submit" name="action">Submit
    <i class="material-icons right">send</i>
  </button> 
    </form>
  </div>

       </div>




       <div class="abso sec" data-scroll-speed="6">
       <h2 class="text-colorb">Search your topics</h2><hr class="grid-header"></br>
       
        <ul class="list-items " >
                <li><a href="">What we do ?</a></li><hr class="hr-list"></br>
                <li><a href="">What we know ?</a></li><hr class="hr-list"><br>
                <li><a href="">How we can help you ?</a></li><hr class="hr-list"></br>
                <li><a href="">Our skills</a></li><hr class="hr-list"></br>
                <li><a href="">Our passion</a></li><hr class="hr-list"></br>
                <li><a href="">What we do ?</a></li><hr class="hr-list"></br>
                <li><a href="">What we know ?</a></li><hr class="hr-list"><br>
                <li><a href="">How we can help you ?</a></li><hr class="hr-list"></br>
                <li><a href="">Our skills</a></li><hr class="hr-list"></br>
                <li><a href="">Our passion</a></li><hr class="hr-list"></br>
                <li><a href="">What we do ?</a></li><hr class="hr-list"></br>
                <li><a href="">What we know ?</a></li><hr class="hr-list"><br>
                <li><a href="">How we can help you ?</a></li><hr class="hr-list"></br>
                <li><a href="">Our skills</a></li><hr class="hr-list"></br>
                <li><a href="">Our passion</a></li><hr class="hr-list"></br>
                <li><a href="">What we do ?</a></li><hr class="hr-list"></br>
                <li><a href="">What we know ?</a></li><hr class="hr-list"><br>
                <li><a href="">How we can help you ?</a></li><hr class="hr-list"></br>
                <li><a href="">Our skills</a></li><hr class="hr-list"></br>
                <li><a href="">Our passion</a></li><hr class="hr-list"></br>
                  </ul>
      

       </div>

     </div>
   </div>
<script>
 $.fn.moveIt = function(){
  var $window = $(window);
  var instances = [];
  
  $(this).each(function(){
    instances.push(new moveItItem($(this)));
  });
  
  window.onscroll = function(){
    var scrollTop = $window.scrollTop();
    instances.forEach(function(inst){
      inst.update(scrollTop);
    });
  }
}

var moveItItem = function(el){
  this.el = $(el);
  this.speed = parseInt(this.el.attr('data-scroll-speed'));
};

moveItItem.prototype.update = function(scrollTop){
  var pos = scrollTop / this.speed;
  this.el.css('transform', 'translateY(' + -pos + 'px)');
};

$(function(){
  $('[data-scroll-speed]').moveIt();
});

</script>

app/views/layouts/_header.html.erb
  <ul id="dropdown1" class="dropdown-content dope-color">
         
          <% Category.all.each do |c| %>
            <li><%= link_to c.name, c %></li>
          <% end%>
        </ul>
        <ul id="dropdown2" class="dropdown-content dope-color">
           <% Category.all.each do |c| %>
            <li><%= link_to c.name, c %></li>
          <% end%>


        </ul>
 <nav id="navigation">

    <div class="nav-wrapper">
      <a href="#!" class="brand-logo" id="logomar">Logo</a>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down" id="navmar">
        
        <li><a href="badges.html">About</a></li>
        <li><a href="#">Designs</a></li>
        <li><a href="#">Code-Support</a></li>
        <li><a class="dropdown-button" href="#" data-activates="dropdown1">Topic-blog</a></li>

        <li><a href="mobile.html">Contact-Us</a></li>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <li><a href="sass.html">About</a></li>
        <li><a href="badges.html">Designs</a></li>
        <li><a href="collapsible.html">Code-Support</a></li>
        <li><a class="dropdown-button" href="#" data-activates="dropdown2">Topic-blog</a></li>
        <li><a href="mobile.html">Contact-Us</a></li>
      </ul>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogweb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Home</h1>
<%= link_to "Blogs", blogs_path%>
<%= link_to "Categories", categories_path%>